export interface SentinelTemplate {
  id: string;
  title: string;
  os: "Windows PowerShell" | "macOS shell";
  description: string;
  scriptFile: string;
  script: string;
  runCommand: string;
  recommended: string[];
}

const WINDOWS_FOLDER_IDLE_SCRIPT = [
  "param(",
  "  [Parameter(Mandatory = $true)]",
  "  [string]$Path,",
  "  [int]$StableSec = 300,",
  "  [int]$PollSec = 5",
  ")",
  "",
  'if (-not (Test-Path -LiteralPath $Path)) {',
  '  Write-Error \"Directory not found: $Path\"',
  "  exit 2",
  "}",
  "",
  'Write-Host \"[FolderSentinel] PID=$PID  Path=$Path  StableSec=$StableSec  PollSec=$PollSec\"',
  "",
  "function Get-Fingerprint([string]$p) {",
  "  $files = Get-ChildItem -LiteralPath $p -File -Recurse -ErrorAction SilentlyContinue",
  "  if (-not $files) { return @{ Count = 0; Bytes = 0; Newest = 0 } }",
  "",
  "  $count  = $files.Count",
  "  $bytes  = ($files | Measure-Object -Property Length -Sum).Sum",
  "  $newest = ($files | Measure-Object -Property LastWriteTimeUtc -Maximum).Maximum.ToFileTimeUtc()",
  "",
  "  return @{ Count = $count; Bytes = [int64]$bytes; Newest = [int64]$newest }",
  "}",
  "",
  "$last = Get-Fingerprint $Path",
  "$stableSince = $null",
  "",
  "while ($true) {",
  "  Start-Sleep -Seconds $PollSec",
  "  $cur = Get-Fingerprint $Path",
  "",
  "  $same = ($cur.Count -eq $last.Count -and $cur.Bytes -eq $last.Bytes -and $cur.Newest -eq $last.Newest)",
  "  $now  = [DateTimeOffset]::UtcNow.ToUnixTimeSeconds()",
  "",
  "  if ($same) {",
  '    if (-not $stableSince) { $stableSince = $now; Write-Host \"[FolderSentinel] Stable started.\" }',
  "    if (($now - $stableSince) -ge $StableSec) {",
  '      Write-Host \"[FolderSentinel] Stable for $StableSec sec. Exiting.\"',
  "      exit 0",
  "    }",
  "  } else {",
  "    $stableSince = $null",
  "    $last = $cur",
  '    Write-Host \"[FolderSentinel] Change detected. Reset timer.\"',
  "  }",
  "}",
].join("\n");

const WINDOWS_NET_IDLE_SCRIPT = [
  "param(",
  "  [int]$StableSec = 300,",
  "  [int]$PollSec = 2,",
  "  [int]$ThresholdKBps = 20",
  ")",
  "",
  'Write-Host \"[NetSentinel] PID=$PID  StableSec=$StableSec  PollSec=$PollSec  Threshold=${ThresholdKBps}KB/s\"',
  "",
  "function Get-TxBytes {",
  "  $stats = Get-NetAdapterStatistics -ErrorAction SilentlyContinue",
  "  if (-not $stats) { return 0 }",
  "  return [int64](($stats | Measure-Object -Property SentBytes -Sum).Sum)",
  "}",
  "",
  "$thresholdBps = [int64]$ThresholdKBps * 1024",
  "$lastBytes = Get-TxBytes",
  "$lastTime = [DateTimeOffset]::UtcNow.ToUnixTimeSeconds()",
  "$stableSince = $null",
  "",
  "while ($true) {",
  "  Start-Sleep -Seconds $PollSec",
  "",
  "  $nowBytes = Get-TxBytes",
  "  $nowTime  = [DateTimeOffset]::UtcNow.ToUnixTimeSeconds()",
  "",
  "  $deltaBytes = $nowBytes - $lastBytes",
  "  $deltaTime  = [Math]::Max(1, ($nowTime - $lastTime))",
  "  $bps = [double]$deltaBytes / $deltaTime",
  "",
  "  $lastBytes = $nowBytes",
  "  $lastTime  = $nowTime",
  "",
  "  if ($bps -le $thresholdBps) {",
  '    if (-not $stableSince) { $stableSince = $nowTime; Write-Host \"[NetSentinel] Under threshold. Stable started.\" }',
  "    if (($nowTime - $stableSince) -ge $StableSec) {",
  '      Write-Host \"[NetSentinel] Under threshold for $StableSec sec. Exiting.\"',
  "      exit 0",
  "    }",
  "  } else {",
  "    $stableSince = $null",
  '    Write-Host (\"[NetSentinel] Active outbound: {0:N0} B/s. Reset.\" -f $bps)',
  "  }",
  "}",
].join("\n");

const MAC_FOLDER_IDLE_SCRIPT = [
  "#!/usr/bin/env bash",
  "set -euo pipefail",
  "",
  'DIR=\"${1:-}\"',
  'STABLE_SEC=\"${2:-300}\"',
  'POLL_SEC=\"${3:-5}\"',
  "",
  'if [[ -z \"$DIR\" ]]; then',
  '  echo \"Usage: $0 <dir> [stable_sec] [poll_sec]\" >&2',
  "  exit 2",
  "fi",
  'if [[ ! -d \"$DIR\" ]]; then',
  '  echo \"Directory not found: $DIR\" >&2',
  "  exit 2",
  "fi",
  "",
  'echo \"[FolderSentinel] PID=$$  Path=$DIR  StableSec=$STABLE_SEC  PollSec=$POLL_SEC\"',
  "",
  "fingerprint() {",
  "  local count=0 bytes=0 newest=0",
  "  while IFS= read -r -d '' f; do",
  "    count=$((count+1))",
  "    local size mtime",
  '    size=\"$(stat -f%z \"$f\" 2>/dev/null || echo 0)\"',
  '    mtime=\"$(stat -f%m \"$f\" 2>/dev/null || echo 0)\"',
  "    bytes=$((bytes + size))",
  "    if (( mtime > newest )); then newest=\"$mtime\"; fi",
  "  done < <(find \"$DIR\" -type f -print0 2>/dev/null)",
  '  echo \"${count}|${bytes}|${newest}\"',
  "}",
  "",
  'last=\"$(fingerprint)\"',
  "stable_since=0",
  "",
  "while true; do",
  "  sleep \"$POLL_SEC\"",
  '  cur=\"$(fingerprint)\"',
  '  now=\"$(date +%s)\"',
  "",
  '  if [[ \"$cur\" == \"$last\" ]]; then',
  '    if (( stable_since == 0 )); then stable_since=\"$now\"; echo \"[FolderSentinel] Stable started.\"; fi',
  "    if (( (now - stable_since) >= STABLE_SEC )); then",
  '      echo \"[FolderSentinel] Stable for $STABLE_SEC sec. Exiting.\"',
  "      exit 0",
  "    fi",
  "  else",
  "    stable_since=0",
  '    last=\"$cur\"',
  '    echo \"[FolderSentinel] Change detected. Reset timer.\"',
  "  fi",
  "done",
].join("\n");

const MAC_NET_IDLE_SCRIPT = [
  "#!/usr/bin/env bash",
  "set -euo pipefail",
  "",
  'STABLE_SEC=\"${1:-300}\"',
  'POLL_SEC=\"${2:-2}\"',
  'THRESHOLD_KBPS=\"${3:-20}\"',
  "",
  "iface=\"$(route -n get default 2>/dev/null | awk '/interface:/{print $2; exit}')\"",
  'if [[ -z \"${iface}\" ]]; then',
  '  echo \"Could not determine default interface.\" >&2',
  "  exit 2",
  "fi",
  "",
  "threshold_bps=$((THRESHOLD_KBPS * 1024))",
  'echo \"[NetSentinel] PID=$$  iface=$iface  StableSec=$STABLE_SEC  PollSec=$POLL_SEC  Threshold=${THRESHOLD_KBPS}KB/s\"',
  "",
  "tx_bytes() {",
  "  netstat -ibn | awk -v iface=\"$iface\" '",
  "    NR==1 {for(i=1;i<=NF;i++){if($i==\"Obytes\") ob=i}}",
  "    NR>1 && $1==iface && ob>0 && $ob ~ /^[0-9]+$/ { if($ob>max) max=$ob }",
  "    END{print max+0}",
  "  '",
  "}",
  "",
  'last_bytes=\"$(tx_bytes)\"',
  'last_time=\"$(date +%s)\"',
  "stable_since=0",
  "",
  "while true; do",
  "  sleep \"$POLL_SEC\"",
  '  now_bytes=\"$(tx_bytes)\"',
  '  now_time=\"$(date +%s)\"',
  "",
  "  delta_bytes=$(( now_bytes - last_bytes ))",
  "  delta_time=$(( now_time - last_time ))",
  "  if (( delta_time <= 0 )); then delta_time=1; fi",
  "",
  "  bps=$(( delta_bytes / delta_time ))",
  "",
  '  last_bytes=\"$now_bytes\"',
  '  last_time=\"$now_time\"',
  "",
  "  if (( bps <= threshold_bps )); then",
  '    if (( stable_since == 0 )); then stable_since=\"$now_time\"; echo \"[NetSentinel] Under threshold. Stable started.\"; fi',
  "    if (( (now_time - stable_since) >= STABLE_SEC )); then",
  '      echo \"[NetSentinel] Under threshold for $STABLE_SEC sec. Exiting.\"',
  "      exit 0",
  "    fi",
  "  else",
  "    stable_since=0",
  '    echo \"[NetSentinel] Active outbound: ${bps} B/s. Reset.\"',
  "  fi",
  "done",
].join("\n");

export const SENTINEL_TEMPLATES: SentinelTemplate[] = [
  {
    id: "windows-folder-idle",
    title: "Folder Idle Sentinel",
    os: "Windows PowerShell",
    description:
      "파일 개수/총용량/최신 수정시간이 안정 구간 동안 변하지 않으면 종료(exit 0)합니다.",
    scriptFile: "sentinel_folder_idle.ps1",
    script: WINDOWS_FOLDER_IDLE_SCRIPT,
    runCommand:
      "powershell -NoProfile -ExecutionPolicy Bypass -File .\\sentinel_folder_idle.ps1 -Path \"D:\\Downloads\" -StableSec 300 -PollSec 5",
    recommended: ["StableSec: 180~600", "PollSec: 2~5"],
  },
  {
    id: "windows-net-idle",
    title: "Network Idle Sentinel (Upload)",
    os: "Windows PowerShell",
    description:
      "Outbound bytes/sec가 임계치 이하로 안정 구간 동안 유지되면 종료(exit 0)합니다.",
    scriptFile: "sentinel_net_idle_upload.ps1",
    script: WINDOWS_NET_IDLE_SCRIPT,
    runCommand:
      "powershell -NoProfile -ExecutionPolicy Bypass -File .\\sentinel_net_idle_upload.ps1 -StableSec 300 -PollSec 2 -ThresholdKBps 20",
    recommended: ["ThresholdKBps: 10~50", "StableSec: 120~600"],
  },
  {
    id: "mac-folder-idle",
    title: "Folder Idle Sentinel",
    os: "macOS shell",
    description:
      "파일 개수/총용량/최신 mtime이 안정 구간 동안 변하지 않으면 종료(exit 0)합니다.",
    scriptFile: "sentinel_folder_idle.sh",
    script: MAC_FOLDER_IDLE_SCRIPT,
    runCommand:
      "chmod +x ./sentinel_folder_idle.sh && ./sentinel_folder_idle.sh \"$HOME/Downloads\" 300 5",
    recommended: ["StableSec: 180~600", "PollSec: 2~5"],
  },
  {
    id: "mac-net-idle",
    title: "Network Idle Sentinel (Upload)",
    os: "macOS shell",
    description:
      "기본 인터페이스 Obytes 증가량을 기준으로 업로드 idle 상태를 감지해 종료(exit 0)합니다.",
    scriptFile: "sentinel_net_idle_upload.sh",
    script: MAC_NET_IDLE_SCRIPT,
    runCommand:
      "chmod +x ./sentinel_net_idle_upload.sh && ./sentinel_net_idle_upload.sh 300 2 20",
    recommended: ["ThresholdKBps: 10~50", "StableSec: 120~600"],
  },
];

export const SENTINEL_OPERATION_STEPS = [
  "선택한 스크립트를 터미널에서 먼저 실행하고 출력되는 PID를 확인합니다.",
  "앱에서 프로세스 목록을 새로고침한 뒤 해당 PID를 선택합니다.",
  "processStableSec은 5~10초로 유지하고, 안정 판정은 센티널의 StableSec으로 조절합니다.",
  "센티널이 종료(exit 0)되면 앱이 finalWarning으로 진입하고, 유예 후 종료를 실행합니다.",
];
